services:
  jamulus-fetch:
    image: ghcr.io/dtinth/jamulus-fetch:latest
    expose:
      - "8080"
    pull_policy: always
    environment:
      - PORT=8080
      - ALLOWED_SERVERS=${ALLOWED_SERVERS:-default}
      - AUTH_TOKEN=${AUTH_TOKEN:-}
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    restart: unless-stopped
